# Site settings
title: Alejandro Planchart
email: planchar@music.ucsb.edu
description: "Early music edited by Alejandro Planchart"
baseurl: ""
url: "http://planchart.github.io"
#twitter_username: jekyllrb
github_username:  planchart

# Build settings
markdown: kramdown
permalink: pretty


# https://help.github.com/articles/sitemaps-for-github-pages
gems:
  - jekyll-sitemap

# Keeping Jekyll up-to-date:
#https://help.github.com/articles/using-jekyll-with-pages#keeping-jekyll-up-to-date
# "bundle update" will update


###################################################
##
## jekyll commands
##    http://jekyllrb.com/docs/usage
##
#
# Comple the source files into the static HTML website
#    jekyll build
#
# Run jekyll server in the background:
#     jekyll serve --detach
# Watch for changes in source files:
#     jekyll serve --watch


#################################################
##
## Jekyll directory structure:
##     http://jekyllrb.com/docs/structure
#
#

